### PR TITLE
 getRelativeTo gets confused when there are multiple occurences of the same separator in the string

### PR DESCRIPTION
**Pull request by PauloMigAlmeida**
This PR address the issue #9 

Let me know if you need any information from me to get this PR approved.

Best regards,

Paulo Almeida

### CODE REVIEW

**Comment by PauloMigAlmeida** [comment]
ping @jarradseers

**Comment by felipeplets** [comment]
@PauloMigAlmeida as I see now you solved an issue related to one I've solved #16 
Both solve different problems changing the same part of the code so I think we can try to solve both with one unique implementation.
My current solution would be to not use the full file path but relative path, so in this case you would always get the last part of the string solving your issue and if using my code it would also solve my issue. 
What do you think?

**Comment by PauloMigAlmeida** [comment]
Hi @felipeplets,

Thanks for you message, I appreciate your time taking a look at it.

As much as I like you idea, I tend not to believe this will be a good investment of our time. Not because isn't worthwhile, but because the owner of this repository hasn't even commented on any of the PRs proposed in the last 6 months. 

If he starts looking at the issues/PRs again, I will be more than happy to do this single implementation with you @felipeplets. 

Best regards,

**Comment by felipeplets** [comment]
Hello @PauloMigAlmeida,

I've sent #17 to @jarradseers, if he does no answer in the next days I believe we can fork it and start a new project.

Are you using express-load or consign in your projects?

All the best,
Felipe

**Pull request merged**
